### ISSUE TITLE
Bug with the custom blocks and the sidebar on mobile devices

### ISSUE THREAD

**Issue by MrAnyx** [leafsphp/leaf-docs-theme#1]
## Description

I recently visited the documentation of [LeafPHP](https://leafphp.dev/) which was made using vitepress and leaf-docs-theme and 
i feel like it is a bit buggy.

The little icon on custom blocks is now above the sidebar when it is expanded on mobile devices.

This id probably just a `z-index` problem.

## Screenshots

![image](https://user-images.githubusercontent.com/44176707/182211020-e6302215-5bfa-4bb0-9ac6-64f48a798a6d.png)
![image](https://user-images.githubusercontent.com/44176707/182211045-8623fcc6-4024-4a74-bb7a-786a395236c0.png)

**Comment by mychidarko** [comment]
This has been fixed now
